// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Saga.Server.Data;
using Saga.Server.Models;

#nullable disable

namespace Saga.Server.Migrations
{
    [DbContext(typeof(SagaDbContext))]
    partial class SagaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Saga.Server.Models.Aktivite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<AktiviteTuru>("AktiviteTuru")
                        .HasColumnType("aktivite_turu")
                        .HasColumnName("aktivite_turu");

                    b.Property<long?>("IcerikId")
                        .HasColumnType("bigint")
                        .HasColumnName("icerik_id");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("kullanici_id");

                    b.Property<long?>("ListeId")
                        .HasColumnType("bigint")
                        .HasColumnName("liste_id");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturulma_zamani");

                    b.Property<long?>("PuanlamaId")
                        .HasColumnType("bigint")
                        .HasColumnName("puanlama_id");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean")
                        .HasColumnName("silindi");

                    b.Property<string>("Veri")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("veri");

                    b.Property<long?>("YorumId")
                        .HasColumnType("bigint")
                        .HasColumnName("yorum_id");

                    b.HasKey("Id");

                    b.HasIndex("IcerikId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ListeId");

                    b.HasIndex("PuanlamaId");

                    b.HasIndex("YorumId");

                    b.ToTable("aktiviteler");
                });

            modelBuilder.Entity("Saga.Server.Models.Bildirim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AliciId")
                        .HasColumnType("uuid")
                        .HasColumnName("alici_id");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("baslik");

                    b.Property<Guid?>("GonderenId")
                        .HasColumnType("uuid")
                        .HasColumnName("gonderen_id");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text")
                        .HasColumnName("link_url");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mesaj");

                    b.Property<bool>("Okundu")
                        .HasColumnType("boolean")
                        .HasColumnName("okundu");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturulma_zamani");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean")
                        .HasColumnName("silindi");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tip");

                    b.HasKey("Id");

                    b.HasIndex("AliciId");

                    b.HasIndex("GonderenId");

                    b.ToTable("bildirimler");
                });

            modelBuilder.Entity("Saga.Server.Models.Icerik", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<ApiKaynak>("ApiKaynagi")
                        .HasColumnType("api_kaynak")
                        .HasColumnName("api_kaynagi");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("baslik");

                    b.Property<int>("GoruntulemeSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("goruntuleme_sayisi");

                    b.Property<DateTime>("GuncellemeZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("guncelleme_zamani");

                    b.Property<string>("HariciId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("harici_id");

                    b.Property<int>("ListeyeEklenmeSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("listeye_eklenme_sayisi");

                    b.Property<string>("MetaVeri")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_veri");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturulma_zamani");

                    b.Property<decimal>("OrtalamaPuan")
                        .HasColumnType("numeric")
                        .HasColumnName("ortalama_puan");

                    b.Property<decimal>("PopulerlikSkoru")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasColumnName("populerlik_skoru");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text")
                        .HasColumnName("poster_url");

                    b.Property<int>("PuanlamaSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("puanlama_sayisi");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean")
                        .HasColumnName("silindi");

                    b.Property<IcerikTuru>("Tur")
                        .HasColumnType("icerik_turu")
                        .HasColumnName("tur");

                    b.Property<DateOnly?>("YayinTarihi")
                        .HasColumnType("date")
                        .HasColumnName("yayin_tarihi");

                    b.Property<int>("YorumSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("yorum_sayisi");

                    b.HasKey("Id");

                    b.ToTable("icerikler");
                });

            modelBuilder.Entity("Saga.Server.Models.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Biyografi")
                        .HasColumnType("text")
                        .HasColumnName("biyografi");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eposta");

                    b.Property<int>("GirisSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("giris_sayisi");

                    b.Property<string>("GoruntulemeAdi")
                        .HasColumnType("text")
                        .HasColumnName("goruntuleme_adi");

                    b.Property<DateTime>("GuncellemeZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("guncelleme_zamani");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kullanici_adi");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturulma_zamani");

                    b.Property<KullaniciRol>("Rol")
                        .HasColumnType("kullanici_rol")
                        .HasColumnName("rol");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean")
                        .HasColumnName("silindi");

                    b.Property<DateTime?>("SonGirisZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("son_giris_zamani");

                    b.HasKey("Id");

                    b.ToTable("kullanicilar");
                });

            modelBuilder.Entity("Saga.Server.Models.KutuphaneDurumu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("BaslangicTarihi")
                        .HasColumnType("date")
                        .HasColumnName("baslangic_tarihi");

                    b.Property<DateOnly?>("BitisTarihi")
                        .HasColumnType("date")
                        .HasColumnName("bitis_tarihi");

                    b.Property<KutuphaneDurum>("Durum")
                        .HasColumnType("kutuphane_durum")
                        .HasColumnName("durum");

                    b.Property<DateTime>("GuncellemeZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("guncelleme_zamani");

                    b.Property<long>("IcerikId")
                        .HasColumnType("bigint")
                        .HasColumnName("icerik_id");

                    b.Property<decimal>("Ilerleme")
                        .HasColumnType("numeric")
                        .HasColumnName("ilerleme");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("kullanici_id");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturulma_zamani");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean")
                        .HasColumnName("silindi");

                    b.HasKey("Id");

                    b.HasIndex("IcerikId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("kutuphane_durumlari");
                });

            modelBuilder.Entity("Saga.Server.Models.Liste", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad");

                    b.Property<DateTime>("GuncellemeZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("guncelleme_zamani");

                    b.Property<bool>("HerkeseAcik")
                        .HasColumnType("boolean")
                        .HasColumnName("herkese_acik");

                    b.Property<int>("IcerikSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("icerik_sayisi");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("kullanici_id");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturulma_zamani");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean")
                        .HasColumnName("silindi");

                    b.Property<ListeTuru>("Tur")
                        .HasColumnType("liste_turu")
                        .HasColumnName("tur");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("listeler");
                });

            modelBuilder.Entity("Saga.Server.Models.ListeIcerigi", b =>
                {
                    b.Property<long>("ListeId")
                        .HasColumnType("bigint")
                        .HasColumnName("liste_id")
                        .HasColumnOrder(0);

                    b.Property<long>("IcerikId")
                        .HasColumnType("bigint")
                        .HasColumnName("icerik_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("EklenmeZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eklenme_zamani");

                    b.Property<string>("NotMetni")
                        .HasColumnType("text")
                        .HasColumnName("not_metni");

                    b.Property<int>("Sira")
                        .HasColumnType("integer")
                        .HasColumnName("sira");

                    b.HasKey("ListeId", "IcerikId");

                    b.HasIndex("IcerikId");

                    b.ToTable("liste_icerikleri");
                });

            modelBuilder.Entity("Saga.Server.Models.Puanlama", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("GuncellemeZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("guncelleme_zamani");

                    b.Property<long>("IcerikId")
                        .HasColumnType("bigint")
                        .HasColumnName("icerik_id");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("kullanici_id");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturulma_zamani");

                    b.Property<decimal>("Puan")
                        .HasColumnType("numeric")
                        .HasColumnName("puan");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean")
                        .HasColumnName("silindi");

                    b.HasKey("Id");

                    b.HasIndex("IcerikId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("puanlamalar");
                });

            modelBuilder.Entity("Saga.Server.Models.Takip", b =>
                {
                    b.Property<Guid>("TakipEdenId")
                        .HasColumnType("uuid")
                        .HasColumnName("takip_eden_id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("TakipEdilenId")
                        .HasColumnType("uuid")
                        .HasColumnName("takip_edilen_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturulma_zamani");

                    b.HasKey("TakipEdenId", "TakipEdilenId");

                    b.HasIndex("TakipEdilenId");

                    b.ToTable("takipler");
                });

            modelBuilder.Entity("Saga.Server.Models.Yorum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Baslik")
                        .HasColumnType("text")
                        .HasColumnName("baslik");

                    b.Property<int>("BegeniSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("begeni_sayisi");

                    b.Property<DateTime?>("GuncellemeZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("guncelleme_zamani");

                    b.Property<long>("IcerikId")
                        .HasColumnType("bigint")
                        .HasColumnName("icerik_id");

                    b.Property<string>("IcerikMetni")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icerik");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("kullanici_id");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturulma_zamani");

                    b.Property<decimal?>("Puan")
                        .HasColumnType("numeric")
                        .HasColumnName("puan");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean")
                        .HasColumnName("silindi");

                    b.Property<bool>("SpoilerIceriyor")
                        .HasColumnType("boolean")
                        .HasColumnName("spoiler_iceriyor");

                    b.Property<long?>("UstYorumId")
                        .HasColumnType("bigint")
                        .HasColumnName("ust_yorum_id");

                    b.HasKey("Id");

                    b.HasIndex("IcerikId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UstYorumId");

                    b.ToTable("yorumlar");
                });

            modelBuilder.Entity("Saga.Server.Models.YorumBegeni", b =>
                {
                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("kullanici_id")
                        .HasColumnOrder(0);

                    b.Property<long>("YorumId")
                        .HasColumnType("bigint")
                        .HasColumnName("yorum_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturulma_zamani");

                    b.HasKey("KullaniciId", "YorumId");

                    b.HasIndex("YorumId");

                    b.ToTable("yorum_begenileri");
                });

            modelBuilder.Entity("Saga.Server.Models.Aktivite", b =>
                {
                    b.HasOne("Saga.Server.Models.Icerik", "Icerik")
                        .WithMany()
                        .HasForeignKey("IcerikId");

                    b.HasOne("Saga.Server.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saga.Server.Models.Liste", "Liste")
                        .WithMany()
                        .HasForeignKey("ListeId");

                    b.HasOne("Saga.Server.Models.Puanlama", "Puanlama")
                        .WithMany()
                        .HasForeignKey("PuanlamaId");

                    b.HasOne("Saga.Server.Models.Yorum", "Yorum")
                        .WithMany()
                        .HasForeignKey("YorumId");

                    b.Navigation("Icerik");

                    b.Navigation("Kullanici");

                    b.Navigation("Liste");

                    b.Navigation("Puanlama");

                    b.Navigation("Yorum");
                });

            modelBuilder.Entity("Saga.Server.Models.Bildirim", b =>
                {
                    b.HasOne("Saga.Server.Models.Kullanici", "Alici")
                        .WithMany()
                        .HasForeignKey("AliciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saga.Server.Models.Kullanici", "Gonderen")
                        .WithMany()
                        .HasForeignKey("GonderenId");

                    b.Navigation("Alici");

                    b.Navigation("Gonderen");
                });

            modelBuilder.Entity("Saga.Server.Models.KutuphaneDurumu", b =>
                {
                    b.HasOne("Saga.Server.Models.Icerik", "Icerik")
                        .WithMany()
                        .HasForeignKey("IcerikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saga.Server.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icerik");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Saga.Server.Models.Liste", b =>
                {
                    b.HasOne("Saga.Server.Models.Kullanici", "Kullanici")
                        .WithMany("Listeleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Saga.Server.Models.ListeIcerigi", b =>
                {
                    b.HasOne("Saga.Server.Models.Icerik", "Icerik")
                        .WithMany()
                        .HasForeignKey("IcerikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saga.Server.Models.Liste", "Liste")
                        .WithMany("Icerikler")
                        .HasForeignKey("ListeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icerik");

                    b.Navigation("Liste");
                });

            modelBuilder.Entity("Saga.Server.Models.Puanlama", b =>
                {
                    b.HasOne("Saga.Server.Models.Icerik", "Icerik")
                        .WithMany()
                        .HasForeignKey("IcerikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saga.Server.Models.Kullanici", "Kullanici")
                        .WithMany("Puanlamalari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icerik");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Saga.Server.Models.Takip", b =>
                {
                    b.HasOne("Saga.Server.Models.Kullanici", "TakipEden")
                        .WithMany("Takipler")
                        .HasForeignKey("TakipEdenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Saga.Server.Models.Kullanici", "TakipEdilen")
                        .WithMany("TakipEdenler")
                        .HasForeignKey("TakipEdilenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TakipEden");

                    b.Navigation("TakipEdilen");
                });

            modelBuilder.Entity("Saga.Server.Models.Yorum", b =>
                {
                    b.HasOne("Saga.Server.Models.Icerik", "Icerik")
                        .WithMany()
                        .HasForeignKey("IcerikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saga.Server.Models.Kullanici", "Kullanici")
                        .WithMany("Yorumlari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saga.Server.Models.Yorum", "UstYorum")
                        .WithMany("Yanitlar")
                        .HasForeignKey("UstYorumId");

                    b.Navigation("Icerik");

                    b.Navigation("Kullanici");

                    b.Navigation("UstYorum");
                });

            modelBuilder.Entity("Saga.Server.Models.YorumBegeni", b =>
                {
                    b.HasOne("Saga.Server.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saga.Server.Models.Yorum", "Yorum")
                        .WithMany("Begenenler")
                        .HasForeignKey("YorumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Yorum");
                });

            modelBuilder.Entity("Saga.Server.Models.Kullanici", b =>
                {
                    b.Navigation("Listeleri");

                    b.Navigation("Puanlamalari");

                    b.Navigation("TakipEdenler");

                    b.Navigation("Takipler");

                    b.Navigation("Yorumlari");
                });

            modelBuilder.Entity("Saga.Server.Models.Liste", b =>
                {
                    b.Navigation("Icerikler");
                });

            modelBuilder.Entity("Saga.Server.Models.Yorum", b =>
                {
                    b.Navigation("Begenenler");

                    b.Navigation("Yanitlar");
                });
#pragma warning restore 612, 618
        }
    }
}
